#!/bin/bash
echo "*********************************************************"
echo "Running git pre-commit hook. Running Static analysis... "
echo "*********************************************************"

#TODO figure out how to pass lint without minifyEnabled
(cd android && ./gradlew ktlintCheck)

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no problems."
    exit 0
else
    echo "*********************************************************"
    echo "       ********************************************      "
    echo 1>&2 "Static analysis found violations it could not fix."
    echo "Run ./gradlew ktlintFormat to fix formatting related issues..."
    echo "       ********************************************      "
    echo "*********************************************************"
    exit 1
fi